apiVersion: v1
kind: Pod
metadata:
  name: jmeter
spec:
  restartPolicy: Never
  containers:
  - name: jmeter
    image: justb4/jmeter:5.4
    workingDir: /opt/test
    command: ["sh","-c","jmeter -Dlog_level.jmeter=DEBUG \
                        -JTARGET_PROTOCOL=http \
                        -JTARGET_HOST=192.168.1.121 -JTARGET_PORT=3000 \
                        -JTARGET_PATH=/api/v1 -JTHREADS=20 \
                        -n -f -t ./test-plan.jmx -l ./test-plan.jtl -j ./jmeter.log \
                        -e -o ./report"]
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    env:
      - name: IMAGE_TIMEZONE
        value: America/Guayaquil
    volumeMounts:
      - name: host-mount
        mountPath: /opt/test
  volumes:
    - name: host-mount
      hostPath:
        path: /home/jenkins/agent/workspace/testpipeline
        type: Directory