pipeline {
    agent any
    stages {
        stage('Clone repo') {
            steps {
                git branch: 'main', url: 'https://github.com/KLaboratory/jmeter-test.git'
            }
        }
        stage('Execute Sanity test') {
            steps {
                sh 'jmeter -n -f -t ./test_plan.jmx -l ./results.jtl -j ./test.log -e -o ./test1'
            }
        }
        stage('Publish Report') {
            steps {
                perfReport filterRegex: '', sourceDataFiles: '*.jtl'
            }
        }
    }
}