pipeline {
    agent any
    stages {
        stage('Clone repo') {
            steps {
                git branch: 'main', url: 'https://github.com/KLaboratory/jmeter-test.git'
            }
        }
        stage('Execute Sanity test') {
            steps {
                sh 'jmeter -Dlog_level.jmeter=DEBUG \
                        -JTARGET_PROTOCOL=http \
                        -JTARGET_HOST=localhost -JTARGET_PORT=3000 \
                        -JTARGET_PATH=/api/v1 -JTHREADS=20 \
                        -n -f -t ./test-plan.jmx -l ./test-plan.jtl -j ./jmeter.log \
                        -e -o ./report'
            }
        }
        stage('Publish Report') {
            steps {
                perfReport filterRegex: '', sourceDataFiles: '*.jtl'
            }
        }
    }
}